name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24', '25']
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Yarn
        run: |
          corepack enable
          yarn --version
      - run: yarn install --immutable
      - run: yarn test --coverage
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.node-version == '24'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info,./coverage/clover.xml
          fail_ci_if_error: true
